#!/bin/bash
yum update -y
yum install httpd -y
service httpd start
chkconfig httpd on
cd /var/www/html
echo "<html><h1>Hello from Wade</h1></html>" > index.html
aws s3 mb s3://esstag2020jan2
aws s3 cp index.html s3://esstag2020jan2
